import pygame

from src.hack.hack_config import R0, R15, SCREEN, KBD

# Constatns Values
SPECIAL_KEYS = {
    pygame.K_RETURN: 128, pygame.K_BACKSPACE: 129,
    pygame.K_LEFT: 130, pygame.K_UP: 131, pygame.K_RIGHT: 132, pygame.K_DOWN: 133,
    pygame.K_HOME: 134, pygame.K_END: 135, pygame.K_PAGEUP: 136,
    pygame.K_PAGEDOWN: 137, pygame.K_INSERT: 138, pygame.K_DELETE: 139,
    pygame.K_ESCAPE: 140, pygame.K_F1: 141, pygame.K_F2: 142, pygame.K_F3: 143,
    pygame.K_F4: 144, pygame.K_F5: 145, pygame.K_F6: 146, pygame.K_F7: 147,
    pygame.K_F8: 148, pygame.K_F9: 149, pygame.K_F10: 150, pygame.K_F11: 151,
    pygame.K_F12: 152,
}
        
# -------------------------------------------- Window --------------------------------------------
WINDOW_SIZE = (1280, 720)
WINDOW_WIDTH, WINDOW_HEIGHT = WINDOW_SIZE
WINDOW_TITLE = "Hack Computer Emulator"

WINDOW_FPS = 120


# --------------------------------------------- GUI ---------------------------------------------
MAX_GUI_SPEED = 1000
DEFALUT_GUI_SPEED = 1000
MIN_GUI_SPEED = 100
GUI_SPEED_CHANGE = 100

# -------------------------------------------- Colors --------------------------------------------
COLOR_TEXT_TITLE = "#7a8294" 
COLOR_TEXT_DEFAULT = "#bcc0c8"
COLOR_TEXT_YELLOW = "#dc9949" 
COLOR_TEXT_BLUE = "#64b4e6"
COLOR_TEXT_GREEN = "#71bc83"
COLOR_TEXT_RED = "#800020"

COLOR_SCREEN_DEFAULT = "#ffffff"
COLOR_SCREEN_BLACK = "#000000"

COLOR_PANEL_BACKGROUND = "#343c4e"
COLOR_PANEL_BORDER= "#ffffff"
COLOR_PANEL_CHOOSE_ROW = "#ffffff"

COLOR_WINDOW_BACKGROUND = "#12141a"


COLOR_BUTTON_TEXT = "#71bc83"
COLOR_BUTTON_MAIN = "#343c4e"
COLOR_BUTTON_SECOND = "#12141a"
COLOR_BUTTON_BORDER = "#dc9949"

# --------------------------------------------- Widgets --------------------------------------------
PANEL_GAP = 20
EMPTY = None

EMULATOR_SCREEN_SIZE = (512, 256)
EMULATOR_SCREEN_WIDTH, EMULATOR_SCREEN_HEIGHT = EMULATOR_SCREEN_SIZE


PANEL_TITLE_FONT = "liberationserif"
PANEL_TEXT_FONT = "Arial"


# Panel Registers
PANEL_REGISTERS_POS = (PANEL_GAP + EMULATOR_SCREEN_WIDTH + PANEL_GAP, PANEL_GAP)
PANEL_REGISTERS_SIZE = (450, 256)
PANEL_REGISTERS_TABLE_SIZE = (4, 4)

PANEL_REGISTERS_TITLE = "Registers"
PANEL_REGISTERS_TITLE_FONT_SIZE = 35
PANEL_REGISTERS_TITLE_POS = (10, 10)

PANEL_REGISTERS_TEXT_FONT_SIZE = 15

PANEL_REGISTERS_DATA_SAMPLE = [
    ["A",  "0", "0x0000", "0" * 16],
    ["D",  "0", "0x0000", "0" * 16],
    ["M",  "0", "0x0000", "0" * 16],
    ["PC", "0", "0x0000", "0" * 16],
]
PANEL_REGISTERS_COLORS = [
    [COLOR_TEXT_TITLE, COLOR_TEXT_BLUE, COLOR_TEXT_BLUE, COLOR_TEXT_BLUE],
    [COLOR_TEXT_TITLE, COLOR_TEXT_BLUE, COLOR_TEXT_BLUE, COLOR_TEXT_BLUE],
    [COLOR_TEXT_TITLE, COLOR_TEXT_YELLOW, COLOR_TEXT_YELLOW, COLOR_TEXT_YELLOW],
    [COLOR_TEXT_TITLE, COLOR_TEXT_DEFAULT, COLOR_TEXT_DEFAULT, COLOR_TEXT_DEFAULT],
]

PANEL_REGISTERS_COLS_RATIOS = [
    4, 5, 6, 16
]

PANEL_REGISTERS_GAPS = (15, 30)


# Panel RAM 
def get_ram_name(address: int):
    """
        Function to get ram name if exists
    """
    if 0 <= address <= 15:
        return f"R{address}"
    
    elif SCREEN <= address < KBD:
        return f"Screen {address - SCREEN}"
    
    elif address == KBD:
        return "KBD"
    
    return ""       

PANEL_RAM_SIZE = (
    512,
    WINDOW_HEIGHT - PANEL_GAP * 3 - EMULATOR_SCREEN_HEIGHT
)

PANEL_RAM_POS = (
    PANEL_GAP,
    PANEL_GAP * 2 + EMULATOR_SCREEN_HEIGHT
)

PANEL_RAM_TABLE_SIZE = (16, 5)

PANEL_RAM_TITLE = "RAM"
PANEL_RAM_TITLE_FONT_SIZE = 35
PANEL_RAM_TITLE_POS = (10, 10)

PANEL_RAM_TEXT_FONT_SIZE = 15

PANEL_RAM_DATA_SAMPLE = [
    [str(i), get_ram_name(i), "0", "0x0", "0" * 16] for i in range(PANEL_RAM_TABLE_SIZE[0])
]
PANEL_RAM_COLORS = [
    [COLOR_TEXT_DEFAULT for _ in range(PANEL_RAM_SIZE[1])] for __ in range(PANEL_RAM_SIZE[0])
]
PANEL_RAM_COLS_RATIOS = [
    5, 10, 5, 6, 16
]

PANEL_RAM_GAPS = (10, 10)


# Panel ROM
PANEL_ROM_SIZE = (
    350,
    WINDOW_HEIGHT - PANEL_GAP * 3 - PANEL_REGISTERS_SIZE[1]
)

PANEL_ROM_POS = (
    PANEL_GAP + EMULATOR_SCREEN_WIDTH + PANEL_GAP,
    PANEL_GAP * 2 + PANEL_REGISTERS_SIZE[1]
)

PANEL_ROM_TABLE_SIZE = (20, 3)

PANEL_ROM_TITLE = "ROM {disassemble live}"
PANEL_ROM_TITLE_FONT_SIZE = 30
PANEL_ROM_TITLE_POS = (10, 10)

PANEL_ROM_TEXT_FONT_SIZE = 15

PANEL_ROM_DATA_SAMPLE = [
    ["0", "0000000000000000", ""] for _ in range(PANEL_ROM_SIZE[0])
]
PANEL_ROM_COLORS = [
    [COLOR_TEXT_DEFAULT for _ in range(PANEL_ROM_TABLE_SIZE[1])] for __ in range(PANEL_ROM_SIZE[0])
]
PANEL_ROM_COLS_RATIOS = [5, 16, 8]

PANEL_ROM_GAPS = (10, 10)

# Panel ROM
PANEL_STATE_RUNNING = "RUNNING"
PANEL_STATE_PAUSED = "PAUSED"

PANEL_STATE_SIZE = (
    WINDOW_WIDTH - EMULATOR_SCREEN_WIDTH - PANEL_REGISTERS_SIZE[0] - PANEL_GAP * 4,
    PANEL_REGISTERS_SIZE[1]
)

PANEL_STATE_POS = (
    PANEL_REGISTERS_POS[0] + PANEL_REGISTERS_SIZE[0] + PANEL_GAP,
    PANEL_GAP
)

PANEL_STATE_TABLE_SIZE = (3, 2)

PANEL_STATE_TITLE = "State"
PANEL_STATE_TITLE_FONT_SIZE = 35
PANEL_STATE_TITLE_POS = (10, 10)

PANEL_STATE_TEXT_FONT_SIZE = 15

PANEL_STATE_DATA_SAMPLE = [
    ["Program", "no prog"],
    ["State", PANEL_STATE_PAUSED],
    ["Speed", "low [----*----] high"],
]


PANEL_STATE_COLORS = [
    [COLOR_TEXT_TITLE, COLOR_TEXT_DEFAULT],
    [COLOR_TEXT_TITLE, COLOR_TEXT_RED],
    [COLOR_TEXT_TITLE, COLOR_TEXT_DEFAULT]
]

PANEL_STATE_COLS_RATIOS = [7, 15]

PANEL_STATE_GAPS = (10, 10)



# --------------------------------------------- Buttons ---------------------------------------------
BUTTON_TEXT_FONT_NAME = "Arial"


BUTTON_PAUSE_POS = (PANEL_ROM_POS[0] + PANEL_ROM_SIZE[0] + PANEL_GAP, PANEL_ROM_POS[1])
BUTTON_PAUSE_SIZE = ((WINDOW_WIDTH - BUTTON_PAUSE_POS[0] - PANEL_GAP * 2) / 2, 50)
BUTTON_PAUSE_TEXT = "Run / Pause"
BUTTON_PAUSE_FONT_SIZE = 30
BUTTON_PAUSE_BORDERS_SIZE = 10


BUTTON_DECREASE_POS = (BUTTON_PAUSE_POS[0], BUTTON_PAUSE_POS[1] + BUTTON_PAUSE_SIZE[1] + PANEL_GAP)
BUTTON_DECREASE_SIZE = (BUTTON_PAUSE_SIZE[0], BUTTON_PAUSE_SIZE[1])
BUTTON_DECREASE_TEXT = "Speed -"
BUTTON_DECREASE_FONT_SIZE = 30
BUTTON_DECREASE_BORDERS_SIZE = 10

BUTTON_INCREASE_POS = (BUTTON_DECREASE_POS[0] + BUTTON_DECREASE_SIZE[0] + PANEL_GAP, BUTTON_DECREASE_POS[1])
BUTTON_INCREASE_SIZE = (BUTTON_DECREASE_SIZE[0], BUTTON_DECREASE_SIZE[1])
BUTTON_INCREASE_TEXT = "Speed +"
BUTTON_INCREASE_FONT_SIZE = 30
BUTTON_INCREASE_BORDERS_SIZE = 10

BUTTON_RESET_POS = (BUTTON_PAUSE_POS[0], BUTTON_DECREASE_POS[1] + BUTTON_DECREASE_SIZE[1] + PANEL_GAP)
BUTTON_RESET_SIZE = (BUTTON_PAUSE_SIZE[0], BUTTON_PAUSE_SIZE[1])
BUTTON_RESET_TEXT = "Reset"
BUTTON_RESET_FONT_SIZE = 30
BUTTON_RESET_BORDERS_SIZE = 10
