# Constatns Values
WINDOW_SIZE = (1280, 720)
WINDOW_WIDTH, WINDOW_HEIGHT = WINDOW_SIZE

EMULATOR_SCREEN_SIZE = (512, 256)
EMULATOR_SCREEN_WIDTH, EMULATOR_SCREEN_HEIGHT = EMULATOR_SCREEN_SIZE


# Colors 
COLOR_TEXT_TITLE = "text_title"
COLOR_TEXT_DEFAULT = "text_default"
COLOR_TEXT_YELLOW = "text_yellow"
COLOR_TEXT_BLUE = "text_blue"
COLOR_TEXT_GREEN = "text_green"
COLOR_TEXT_RED = "text_red"


COLOR_SCREEN_DEFAULT = "screen_default"
COLOR_SCREEN_BLACK = "screen_black"

COLOR_PANEL_BACKGROUND = "panel_background"
COLOR_WINDOW_BACKGROUND = "windows_background"

COLORS = {
    COLOR_TEXT_TITLE: "#7a8294", 
    COLOR_TEXT_DEFAULT: "#bcc0c8",
    COLOR_TEXT_YELLOW: "#dc9949", 
    COLOR_TEXT_BLUE: "#64b4e6",
    COLOR_TEXT_GREEN: "#71bc83",
    COLOR_TEXT_RED: "#800020",

    COLOR_SCREEN_DEFAULT: "#ffffff",
    COLOR_SCREEN_BLACK: "#000000",

    COLOR_PANEL_BACKGROUND: "#343c4e",
    COLOR_WINDOW_BACKGROUND: "#12141a",
}
