# Constatns Values
WINDOW_SIZE = (1280, 720)
WINDOW_WIDTH, WINDOW_HEIGHT = WINDOW_SIZE
WINDOW_TITLE = "Hack Computer Emulator"

WINDOW_FPS = 120

EMULATOR_SCREEN_SIZE = (512, 256)
EMULATOR_SCREEN_WIDTH, EMULATOR_SCREEN_HEIGHT = EMULATOR_SCREEN_SIZE



COLOR_TEXT_TITLE = "#7a8294" 
COLOR_TEXT_DEFAULT = "#bcc0c8"
COLOR_TEXT_YELLOW = "#dc9949" 
COLOR_TEXT_BLUE = "#64b4e6"
COLOR_TEXT_GREEN = "#71bc83"
COLOR_TEXT_RED = "#800020"

COLOR_SCREEN_DEFAULT = "#ffffff"
COLOR_SCREEN_BLACK = "#000000"

COLOR_PANEL_BACKGROUND = "#343c4e"
COLOR_WINDOW_BACKGROUND = "#12141a"
